### ISSUE TITLE
 drag&drop multiple files fails

### ISSUE THREAD

**Issue by xosos** [Spiritdude/OpenJSCAD.org#106]
Drag&drop multiple files into the file-area on the browser fails, it just happens nothing. Of course, when I only drop one file it works. (Win 7 Ultimate 64-Bit, Firefox 42 or chromo 46)

**Comment by z3dev** [comment]
It seems that support for HTML5 DataTransfer, File, FileReader have changed recently in the browsers. The drag and drop functionality needs some major updates, as well as testing.

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer

**Comment by z3dev** [comment]
@xosos thanks for opening this issue.
I tried drag and drop using both Firefox and Chrome. As you mentioned, a single file works just fine. I was also able to drag and drop several files as well, selecting three files from the examples directory (See the image attached.)
Can you try this simple test on your system?

FYI, Chrome (only) is able to handle a complete directory as well, and read all the files inside the directory.
![1](https://cloud.githubusercontent.com/assets/8969165/11737678/18d1d580-a01f-11e5-9bc3-639c18ddd6a1.jpg)

**Comment by xosos** [comment]
@z3dev thanks for looking into this issue,
still no reaction when dropping three files. Have the additional data contain something special? In my case they contain only one function. 
![dragdrop](https://cloud.githubusercontent.com/assets/16033050/11738018/2f10aadc-9fdf-11e5-8907-f432629155fd.jpg)

**Comment by z3dev** [comment]
Correct. There's a special function called "include()"
One of the scripts must contain main(). And the main script must include("another.jscad") the others.

**Comment by xosos** [comment]
The main file runs without problems. 
At the top of my main file I wrote this to lines:
include('rollingstock.jscad');
include('casLib.jscad');
Could it be that a language-depending file-seperator makes this problem?
![dragdrop](https://cloud.githubusercontent.com/assets/16033050/11740939/1eb452e4-9ff6-11e5-9135-c2a8233b35ae.jpg)

**Comment by xosos** [comment]
I found the problem! When making multiple drag&drop the main-script must be named "main.jscad".
See: Index.html line 827, if gMemFsTotal>1) {...} hi looks only for a "main.jscad" file.

**Comment by z3dev** [comment]
Super.

I'll review the code a little. It would be easier if any file with "main()" could be used.

**Comment by z3dev** [comment]
FYI, this has been fixed in OpenSCAD 0.4.0 release. The files are now scanned for main() to determine which one is the initial source code. So, main() can be defined in any file now.

Please try this out with the new release.
