### ISSUE TITLE
Enhancement: Change Drag n Drop to File Upload

### ISSUE THREAD

**Issue by z3dev** [Spiritdude/OpenJSCAD.org#111]
There are browsers that don't support HTML5 drag and drop. In these case, the Drag and Drop should morph into a simple File upload button, and support all the various file types.

**Comment by z3dev** [comment]
Closing as the enhancement was added in version 0.5.0

**Comment by RolandR** [comment]
Hey,

Sorry for asking this here, but what is the relationship between the version on [openjscad.org](https://openjscad.org) and the one you're referencing?

I still don't see this feature on the main [openjscad.org](https://openjscad.org) site. Should I clone a dev branch or something?

Thanks!

**Comment by z3dev** [comment]
The last release has this feature. Please try the website, www.openjscad.org

Basically, the JavaScript detects that the browser is running on a mobile device (not easy), and then adds a file load button.

Let me know if this doesn't work with your device and or browser.

**Comment by RolandR** [comment]
>Basically, the JavaScript detects that the browser is running on a mobile device (not easy), and then adds a file load button.

Oh, I see!

I think it would be very handy to also have a simple file upload button on desktop.  
I know some people who don't actually have a graphical file browser installed, and in my opinion the drag-and-drop solution adds some unnecessary steps to the process - after all, I still have to navigate to the jscad file regardless of whether I'm doing so in nautilus/explorer/finder or in the browser's "upload file" popup.

\-

By the way, thanks for your work on OpenJSCAD. I use it for pretty much any 3D models I make nowadays.  
Here's a model train wagon written entirely in OpenJSCAD!

![](https://draemm.li/share/img/spur-n/l3.jpg)
