### ISSUE TITLE
OpenJSCAD stl generation error not present in openscad.

### ISSUE THREAD

**Issue by juergenboehm** [Spiritdude/OpenJSCAD.org#115]
If one transforms the scad file

http://www.aviduratas.de/modelpart-025.scad

with openJSCAD one gets

http://www.aviduratas.de/openjscad.stl

transformed with openscad one gets

http://www.aviduratas.de/modelpart-025.stl

A review with netfabb shows, that modelpart-025.stl is correct (only "expected holes", where two polyhedra are connected by a single edge only).

But openjscad.stl contains severe errors, especially the following, where a triangle is inserted, that does not appear in the original .scad file:

http://www.aviduratas.de/openjscad-error.png

**Comment by juergenboehm** [comment]
As I rearranged files on my homepage now the urls are

http://www.aviduratas.de/openjscad/modelpart-025.scad

and so on for the other files

**Comment by z3dev** [comment]
Pull request #107 contains some changes to CSG.js and openjscad.js. I ran some tests and all issues with T-junctions were resolved after making those changes.

If you need this fixed then please make the changes manually.

**Comment by z3dev** [comment]
This issue was moved to jscad/io#14
