### ISSUE TITLE
Non manifold export with AMF exporter

### ISSUE THREAD

**Issue by hovissimo** [Spiritdude/OpenJSCAD.org#126]
Source: https://gist.github.com/hovissimo/ce5366a35834c3690488

Result: http://imgur.com/KRkJ9UI (light blue shows discontinuities)

**Comment by z3dev** [comment]
This is basically the same as the STL import bug, as the same internat routine is used.

**Comment by z3dev** [comment]
This issue was moved to jscad/io#12
