### ISSUE TITLE
fix for url handling with ? in base 

### ISSUE THREAD

**Issue by biscuitlad** [Spiritdude/OpenJSCAD.org#129]
This was spotted by the cloud9 team.  

Essentially their IDE preview panel doesn't work when you have a ? in the url, so trying to load min.html or index.html fails (openjscad.js#L988), but it works if you replace it with L718 where the ? is handled correctly.  

Helps for cloud9 previews, all we need now is a fix for keeping the previous view when rendering a jscad file...  ;-)

**Comment by z3dev** [comment]
A small bug fix was applied to the MASTER branch, openjscad.js
Please try that version. If all is well then I will close this issue.

**Comment by z3dev** [comment]
Closing, as the fix was release with 0.4.0 in Feb 2016.
