### ISSUE TITLE
Bug: Passing link in URL no longer works

### ISSUE THREAD

**Issue by z3dev** [Spiritdude/OpenJSCAD.org#130]
After trying out the latest published version I noticed one feature that I was previously using doesn't seem to work anymore. If you pass openjscad.org a url link it used to load the file into the editor. That functionality is now giving me an error. Is that expected? loading the file by dragging and dropping works as does cutting and pasting the file into the editor.

Here is an example of what I'm referring to using one of my designs:

http://openjscad.org/#https://raw.githubusercontent.com/kak-bo-che/sturdy_box/master/sturdy_box.jscad

Here are also some images of what it is supposed to look like.

http://kak-bo-che.github.io/laser/2016/01/07/sturdy-box.html

**Comment by z3dev** [comment]
Version 0.4.0

**Comment by biscuitlad** [comment]
This is the same error I gave the fix for in the previous issue.  Basically the ? in the base URL is not handled correctly. Replace the lines in openjscad.js with those I suggested and it should work.

**Comment by z3dev** [comment]
Yep. Same bug.
A small bug fix was applied to the MASTER branch, openjscad.js
