### ISSUE TITLE
color transparency fails except for red?

### ISSUE THREAD

**Issue by biscuitlad** [Spiritdude/OpenJSCAD.org#132]
box = color("palegreen", 0.8, box);  //fails
 lid = color("red", 0.8, lid);   //works

Red will be transparent, any other colour seems to fail.  You can swap these and still one will fail and the other work.

**Comment by z3dev** [comment]
@biscuitlad you found a bug. I'm not sure what the issue is at this time, but was able to reproduce the issue.

It seems that other color names do not work, like "blue", "palegreen", etc. And as you mentioned, "red" works.

**Comment by z3dev** [comment]
This issue was moved to jscad/scad-api#3
