### ISSUE TITLE
Issue with core Matrix4x4.translation function

### ISSUE THREAD

**Issue by rasmuskr** [Spiritdude/OpenJSCAD.org#148]
Hey

I am pretty sure that the function CSG.Matrix4x4.translation is broken from:
https://github.com/Spiritdude/OpenJSCAD.org/blob/master/csg.js#L3586

```
// Create an affine matrix for translation:
    CSG.Matrix4x4.translation = function(v) {
        // parse as CSG.Vector3D, so we can pass an array or a CSG.Vector3D
        var vec = new CSG.Vector3D(v);
        var els = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, vec.x, vec.y, vec.z, 1];
        return new CSG.Matrix4x4(els);
    };
```

The matrix should look like this

```
var els = [1, 0, 0, vec.x, 0, 1, 0, vec.y, 0, 0, 1, vec.z, 0, 0, 0, 1];
```

I may fix this and open a PR but dont have the tools at the computer I am currently on.

**Comment by z3dev** [comment]
@rasmuskr Can you open an issue against CSG.js at the following repository? That's the original repository and you'll get faster answers there.

https://github.com/joostn/OpenJsCad

**Comment by z3dev** [comment]
This issue was moved to jscad/csg.js#17
