### ISSUE TITLE
Enhancement: DXF Import

### ISSUE THREAD

**Issue by themaniac** [Spiritdude/OpenJSCAD.org#151]
I'm working on an angular project, could someone tell me if openjscad works with this framework?

then, i need to know if it's possible to import dxf for manipulation.

Thanks in advance

**Comment by z3dev** [comment]
Angular and OpenJSCAD should work together. Try it.

OpenJSCAD.org only exports CAG (2D) objects. No import. See formats.js

**Comment by z3dev** [comment]
@themaniac The latest release, 0.5.0, added SVG import and export. Can you use that?

**Comment by z3dev** [comment]
This issue was moved to jscad/io#10
