### ISSUE TITLE
cylinder({round:true}) incorrectly forces radius to 1

### ISSUE THREAD

**Issue by fischman** [Spiritdude/OpenJSCAD.org#154]
cylinder({r:5, h:10, round:true})
yields a rounded cylinder of radius 1 instead of the specified 5, while
cylinder({r:5, h:10, round:false})
yields a (correct) radius 5 cylinder.

I believe the bug is that these lines:
https://github.com/Spiritdude/OpenJSCAD.org/blob/d376922cdee0630c2ed3333a5ea5eae1b379b5fc/openscad.js#L557
https://github.com/Spiritdude/OpenJSCAD.org/blob/d376922cdee0630c2ed3333a5ea5eae1b379b5fc/openscad.js#L561
pass params |radiusStart| and |radiusEnd| to CSG.roundedCylinder() but that function only accepts |radius| as a param: https://github.com/Spiritdude/OpenJSCAD.org/blob/d376922cdee0630c2ed3333a5ea5eae1b379b5fc/csg.js#L1717

Workaround is to use the latter function directly, at the cost of having to specify |start| and |end| explicitly:
CSG.roundedCylinder({start:[0,0,0],end:[0,0,10], radius: 5})

**Comment by z3dev** [comment]
A definite bug but this might need a change to the CSG library.

function main() {
// using r r1 r2
    var c1 = cylinder({r:3, h:10, round:true}).translate([-20,0,0]);
    var c2 = cylinder({r:3, h:10, round:false}).translate([-10,0,0]);
    var c3 = cylinder({r1:3, r2: 1, h:10, round:true}).translate([0,0,0]);
    var c4 = cylinder({r1:3, r2: 1, h:10, round:false}).translate([10,0,0]);
// using d d1 d2
    var c5 = cylinder({d: 6, h:10, round:true}).translate([-20,10,0]);
    var c6 = cylinder({d: 6, h:10, round:false}).translate([-10,10,0]);
    var c7 = cylinder({d1: 6, d2: 2, h:10, round:true}).translate([0,10,0]);
    var c8 = cylinder({d1: 6, d2: 2, h:10, round:false}).translate([10,10,0]);

   return union(c1,c2,c3,c4,c5,c6,c7,c8);
}

**Comment by fischman** [comment]
Thanks for the quick triage!  
Agreed best fix is to teach CSG.roundedCylinder about radius{Start,End}.

If that's difficult to do with high confidence in short order, how about passing radius and erroring out if cylinder(p) is called with p.r1||p.r2 (since csg.js can't support that until the fix above is made)?

**Comment by z3dev** [comment]
This issue was moved to jscad/scad-api#2
