### ISSUE TITLE
Enhancement: 3MF Support

### ISSUE THREAD

**Issue by z3dev** [Spiritdude/OpenJSCAD.org#160]
http://www.3mf.io/what-is-3mf/

Here's where to start.

**Comment by z3dev** [comment]
And samples for testing can be found at https://github.com/3MFConsortium/3mf-samples

**Comment by kaosat-dev** [comment]
I can tackle this if needed, already worked on 3mf parsing.

**Comment by z3dev** [comment]
@kaosat-dev Sure. We are using a nice XML SAX library for the AMF file parsing. I think that 3MF looks very similar if not the same.

**Comment by z3dev** [comment]
This issue was moved to jscad/io#9
