### ISSUE TITLE
List Comprehension not supported in OpenSCAD translator, weird error messages

### ISSUE THREAD

**Issue by juliendorra** [Spiritdude/OpenJSCAD.org#162]
One of the newest (relatively…) and more powerful feature of OpenSCAD is [list comprehensions](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/List_Comprehensions).

At the moment, they don't work in OpenJSCAD when using OpenSCAD code, and give weird error messages in the interface.

I have updated [the Direct OpenSCAD Source Import doc section](https://en.wikibooks.org/w/index.php?title=OpenJSCAD_User_Guide&stable=0#Direct_OpenSCAD_Source_Import)  to reflect that they are note supported, as a lot of great OpenSCAD designs have incorporated them since a couple of years.

**Comment by z3dev** [comment]
@juliendorra Thanks for the information.

**Comment by z3dev** [comment]
This issue was moved to jscad/openscad-openjscad-translator#15
