### ISSUE TITLE
Question: clarify orientation of skew cylinders/cones

### ISSUE THREAD

**Issue by BenW0** [Spiritdude/OpenJSCAD.org#163]
When I create a CSG.cylinder object, I expect a cylinder parallel to the line between `start` and `end`, with flat end caps perpendicular to the line. However, when I execute the following in openjscad.org (or the debugger on openjscad.github.io), I obtain a cylinder with _skewed_ end caps, not at all what I was expecting.

```
function main(){
    return CSG.cylinder({start:[0,0,0], end:[2, 2, 2], radiusStart:1, radiusEnd:1});
}
```

Output as I see it:

![cylinder](https://cloud.githubusercontent.com/assets/6465507/17134105/23653452-5329-11e6-8f04-9aa2a802936c.png)

This is not the case if any one of the end coordinate elements is 0 (i.e. the cylinder lies in one of the x/y/z planes).

If this is the intended behavior, could you help me understand what is going on? I will be happy to submit a documentation patch once I get my head around what `CSG.cylinder()` is supposed to do so I can write one.

Thanks

**Comment by z3dev** [comment]
This issue was moved to jscad/csg.js#19
