### ISSUE TITLE
Enhancement: STEP Support

### ISSUE THREAD

**Issue by z3dev** [Spiritdude/OpenJSCAD.org#172]
https://en.wikipedia.org/wiki/ISO_10303

**Comment by z3dev** [comment]
Withdrawing this enhancement as this standard is really really old and bad.

**Comment by xialvjun** [comment]
STEP has an update https://en.wikipedia.org/wiki/ISO_10303#2020_updates 
STEP has become the most common manufacturing file format

**Comment by hrgdavor** [comment]
@xialvjun jscad does not have metadata to generate curves for step files. If you want mesh, you can export 3mf and import in tool of choice.
