### ISSUE TITLE
Difference with two 2D prims as arguments causes error.

### ISSUE THREAD

**Issue by rgegriff** [Spiritdude/OpenJSCAD.org#176]
Whenever I attempt to render out the following shape:
```javascript
difference(
  circle({r:1}),
  square({size:[2,2], center:true})
);
```
I get the error `Uncaught TypeError: a[i].setColor is not a function`.

I *can* use `circle.subtract()` but I am working on building a fork of openjscad with a [blockly](https://developers.google.com/blockly/) interface, and the functional style maps really well onto the interface. Is there any (potentially undocumented) way to use 2D primitives in the `difference()` and `intersection()` functions like you can with `union()`?

**Comment by z3dev** [comment]
There's a bug in difference() which has been fixed and will be released in the next version. Would you like patch the library?

Alternatively, you can use the CSG.subtract() function to implement the same.

**Comment by rgegriff** [comment]
I would love to patch that in. I am assuming you are referring to pr #171 . I will merge that in. Thanks! This will help tremendously!
