### ISSUE TITLE
Returning array of CAGs from main() behaves as if they're CSG's

### ISSUE THREAD

**Issue by fischman** [Spiritdude/OpenJSCAD.org#178]
This code incorrectly offers to generate STL for a 2D model; commenting out the first return so that the CAGs are union()d to a single CAG allows correct export as DXF/SVG.

```
function main() {
  let o = [];
  o.push(circle().translate([2,0,0]));
  o.push(circle());
  return o;  // Generates STL
  return union(o);  // Generates DXF
}
```

I think the bug is in [openjscad.js:setCurrentObject()](https://github.com/Spiritdude/OpenJSCAD.org/blob/3968cdfafb13b27e8ee84133e3368a7040754257/openjscad.js#L1036-L1038) in that it doesn't check for CAG vs CSG before assigning `this.currentObject = csg;`

**Comment by z3dev** [comment]
I just tried this with the new release; 0.5.2 (DEV branch). I'm happy to say the bug is fixed. :)

Thanks again for the great help.

**Comment by fischman** [comment]
Great, thanks! :)
