### ISSUE TITLE
Load from remote URL gives an error, no code is loaded

### ISSUE THREAD

**Issue by nataliefreed** [Spiritdude/OpenJSCAD.org#182]
When I try to load an OpenJSCAD file from a remote URL I get the following error:
"The JSCAD script must contain a function main() which returns one or more CSG or CAG solids."

The same issue occurs with this example provided in the user guide, and all other examples I've tried:
http://openjscad.org/#http://openjscad.org/examples/slices/tor.jscad

I've tried this in Chrome, Safari, and Firefox on Max OS X.

This may be the same issue as #130 ?

Thank you.

**Comment by z3dev** [comment]
@nataliefreed Thanks for reporting this. I'll try some examples using the latest DEV release, and let you know.

**Comment by nataliefreed** [comment]
I'm not sure what's changed, but it's working for me now.

**Comment by z3dev** [comment]
@nataliefreed If the current script is saved locally (CTRL-S) then remote URLs are not working. You may have hit this issue. I'm working on a fix to this issue now.

**Comment by nataliefreed** [comment]
Aha! I think that is what I ran into. Thank you for working on it!

**Comment by z3dev** [comment]
Closing as Release 0.5.2 provided the fix.
