### ISSUE TITLE
Function .center() doesn't work anymore

### ISSUE THREAD

**Issue by RolandR** [Spiritdude/OpenJSCAD.org#183]
I may be doing something wrong, but the .center() function seems to not work anymore.

    function main() {
        var foo = cube({size: 3});
        foo = foo.center([true, false, true]);
        return foo;
    }

What I would expect is that the cube would be centered on the X and Z axis, but it has no effect.

I'm pretty sure that it worked in the past, as I have a few models that use .center(), which are now broken.

Thanks for looking into this!

**Comment by RolandR** [comment]
I did some digging - did 8a7b54c fix this?

Sorry that I overlooked that, in that case.

**Comment by z3dev** [comment]
@RolandR thanks for using OpenJSCAD.org

the CSG.center() function is a little strange, and accepts 3 arguments; strings. In order to center an object, please use this...

function main() {
    var foo = cube({size: 3});
    foo = foo.center('x','y','z');
    return foo;
}

**Comment by z3dev** [comment]
By the way, i updated the user guides.

**Comment by RolandR** [comment]
> thanks for using OpenJSCAD.org

Thanks for your work on this great tool! :-)

Yes, changing my arguments to strings worked as intended.
Do you think we should/could add backwards compatibility to accept arrays of booleans as well?
The problem had me stumped for a while, and I might not be the only one.

**Comment by z3dev** [comment]
@RolandR I opened a new enhancement request for the CSG library. When that happens is unknown at this time. I'm going to close this issue now.

However, I'm working on the CSG library now. :)

**Comment by RolandR** [comment]
Apparently, the function changed its behaviour again, back to taking an array of booleans.

This is especially tricky because the previous way still *sometimes* works as expected:

`cube(10).center("x")` happens to do the same as `cube(10).center([true, false, false])`, but for example `cube(10).center("y")` also centers on the x axis.

**Comment by z3dev** [comment]
@RolandR once again... welcome to the world of inconsistent API. we are trying to correct this mess in V2.

It looks like an array of booleans does the trick.

```
    return center([false,false,false], c);
    return c.center([true,true,true]);
```

**Comment by RolandR** [comment]
I just stumbled into another problem with `.center()`: Centering around `z` actually translates by half the object's `y` size.

This was fixed in [this pull request](https://github.com/jscad/csg.js/pull/130) - any idea when we will see it live on openjscad.org?

**Comment by z3dev** [comment]
We have no plans to release a new version of V1, so I hacked the distribution.

Please try again.

**Comment by RolandR** [comment]
I haven't had any issues since - thanks a lot for fixing this!
