### ISSUE TITLE
Error in line 43: Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by tobster-de** [Spiritdude/OpenJSCAD.org#191]
//!OpenSCAD

$fn = 25;

hull()
{
    cylinder(r=5,h=5);    
    translate([0,20]) cylinder(r=5,h=5);
}

**Comment by z3dev** [comment]
@tobster-de Thanks for using OpenJSCAD.org

Sadly, the OPENSCAD translator does not have full functionality, i.e. hull() is not supported. And there's no further development planned as well.

**Comment by z3dev** [comment]
By the way, you can translate the OpenSCAD script to OpenJSCAD syntax. The hull() function exits but with a different syntax.

**Comment by tobster-de** [comment]
It's just that I thought it's working because of [this method](https://github.com/Spiritdude/OpenJSCAD.org/blob/master/openscad.js#L703).

**Comment by z3dev** [comment]
Correct.
However, your script starts with //!OpenSCAD
That invokes the OPENSCAD translator.

**Comment by z3dev** [comment]
OpenSCAD has it's own "language". I'm sure that you know this already based on the example script.

OpenJSCAD.org is written in JavaScript, and OpenJSCAD scripts are written in JavaScript.

There are "compatibility" functions that make the transition from OpenJSCAD to OpenJSCAD easier, but the language differences make 100% compatibility impossible.

That's where the OPENSCAD translator comes in. This small library converts OpenJSCAD scripts to OpenJSCAD scripts, internally. However, it was does not work well with newer or complex OpenJSCAD scripts. And the developer is not maintaining the library.

I'm not sure this is the answer to your question. Please consider the OPENSCAD translator as "experimental".

**Comment by tobster-de** [comment]
I'm fine with that. 

Somehow it's sad, that there's no further development, because it's a fine tool with very fast rendering and a really good look. I'm using it with OpenSCAD because the other online editor site isn't that beautiful.
