### ISSUE TITLE
Bug: initial_csg.canonicalized is not a function

### ISSUE THREAD

**Issue by hobofan** [Spiritdude/OpenJSCAD.org#193]
I am getting this error message when opening the default index.html with the object not rendering:

```
Uncaught TypeError: initial_csg.canonicalized is not a function

csgToMeshes @ openjscad.js?0.5.2:583
setCsg @ openjscad.js?0.5.2:309
updateView @ openjscad.js?0.5.2:1119
setCurrentObjects @ openjscad.js?0.5.2:1073
(anonymous function) @ openjscad.js?0.5.2:1315
w.onmessage @ jscad-worker.js?0.5.2:40
```

I narrowed the breaking change down to https://github.com/Spiritdude/OpenJSCAD.org/commit/df291a90ba601a4a3cf18bcea22eef4bf319f98b. The commit before that one works fine.

**Comment by z3dev** [comment]
@hobofan Interesting. The main improvement of Release 0.5.2 is the retention of the return objects, 1 or more.

What browser are you working with? And on which OS?

**Comment by hobofan** [comment]
@z3dev Chromium 53 on Ubuntu 16.04

**Comment by z3dev** [comment]
@hobofan Interesting indeed.

I develop and test on MacOS with Google Chrome (54 was the latest), but I would guess that Chromium is a slightly different animal.

Can you provide a stack trace from the Javascript console?

**Comment by hobofan** [comment]
Is there supposed to be a longer stack trace than the one in my initial comment? If you tell me how to get more than that, I'd be glad to.

**Comment by z3dev** [comment]
I was hoping so... but maybe not as each browser has different stack traces.

Anyway, I'm not sure why 'initial_csg' is not a proper CSG object. That shouldn't be possible given that previous routines are verifying the returned values from your JSCAD script.

Are any of the examples working?

**Comment by z3dev** [comment]
@hobofan I applied a fix to the MASTER branch of OpenJSCAD.org. Can you try this version?

(Don't use the DEV branch as this is a major work in progress at the moment)

**Comment by hobofan** [comment]
@z3dev Current master works! Thanks!
