### ISSUE TITLE
Repo structure, lack of Unit tests ? 

### ISSUE THREAD

**Issue by kaosat-dev** [Spiritdude/OpenJSCAD.org#199]
Hi everyone ! 
Wanted to start contributing to a (big) bit of an overhaul of the repository (clearer seperation of UI/core/import export etc) , however I did not find any unit tests (other than running OpenJscad on examples and making sure it does not break ?) for any of the core features?
Am I missing something ?
Thanks in advance !

**Comment by z3dev** [comment]
@kaosat-dev This is probably a better question for the DEV topic via the User Group.

I have some scripts that test OpenJSCAD via the command line script. There are no unit tests, although I have started a unit test library for the CSG library. So, it really depends on what you want to test.

See the test results on the WIKI pages. That's how releases are tested today.

**Comment by z3dev** [comment]
I should mention that I'm available via Google Hangouts if you want to chat directly about your changes, merging, new stuff, etc.

**Comment by kaosat-dev** [comment]
thanks for the infos @z3dev !
By User group , do you mean the Google+ community or did I miss something ?
My main concern with tests was avoiding any regression , and without tests , that is not exactly guaranteed :)

I am currently looking at what the command line script does, and would propose putting those into a something runnable via node.js (for minimal automated testing) so that we can have a clear output on failing /non failing test & expectations (I am willing to make the script and to setup all that is needed).

**Comment by z3dev** [comment]
I feel the same, and started simply. I'll package up what I have, including the test files used for input.

How do you want to organize the test suites? A new repository? That would test the NPM packaging as well.

Keep in mind that the browser testing takes a lot of manual effort. There's no other way to guarantee compatibility.

**Comment by z3dev** [comment]
The issues are monitored by myself and Rene. This is really the development area.

If you are looking for feedback from others then Google+ groups are best.

**Comment by kaosat-dev** [comment]
Ok thanks a lot for the information ! 
Some basic unit tests are now added as part of PR #200 , and I will try to add more automated tests in the future.
