### ISSUE TITLE
Release 0.6.0 Testing

### ISSUE THREAD

**Issue by z3dev** [Spiritdude/OpenJSCAD.org#237]
This is a discussion for Release 0.6.0 which will probably take a few interrelations to produce successfully and completely. And there may be a few issues discovered along the way as well.

First issue... Didn't take long.

This branch (DEV) is 390 commits ahead, 3 commits behind master.

**Comment by z3dev** [comment]
I did a pull of DEV, and then NPM install on OSX. It seems that there's a module being rebuild from C source code; node-gyp rebuild

Lots of ugly errors...

But installation seems fine.

**Comment by z3dev** [comment]
Issue: Initial installation is missing dist/opt.js, which is used by viewer-options.html

npm run build-opt

fails

**Comment by z3dev** [comment]
Reset View does not work. "TypeError: gProcessor.viewer.reset is not a function"
(See the left side menu, control-RETURN)

**Comment by z3dev** [comment]
Safari 9.1.3 only shows white screen... no models.

SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.
    (anonymous function) ... index.js: 14141

**Comment by z3dev** [comment]
Viewer does not reset perspective when window size changes. After resizing, perspectives are skewed.

**Comment by z3dev** [comment]
View on iOS does not rotate, pan, zoom, etc.

**Comment by kaosat-dev** [comment]
1 - that is very likely node-sylvester, used in the openscad-openjscad-translator : it works fine , no need to be scared of the weird build :)
2 - will take a look , fix should be trivial...hmm although the build file is gone too ? need to investigate
3 - Safari 10.0 works nothing I can do for old versions as Safari is force updated along with the system
4 - Viewer has not been changed recently, so I would argue that we postpone any changes/fixes there until AFTER this release , as the viewer is a mess and needs major rethinking

**Comment by lorenzoaspesi** [comment]
On my machine I have no errors running `npm install`, but I have errors on `npm run build-cli`:
`Could not resolve 'csg' from /home/lori/Documenti/OpenJSCAD.org-dev/node_modules/@jscad/scad-api/src/primitives3d.js`

I can't get why it doesn't work, since both `rollup.config.module.js` and `node_modules/@jscad/csg/csg.js` look right.

There is the full output as an attachment.
[npm run build-cli output.txt](https://github.com/Spiritdude/OpenJSCAD.org/files/923569/npm.run.build-cli.output.txt)

**Comment by kaosat-dev** [comment]
Thanks for the feedback @lorenzoaspesi 
now I know what that is due to ! I think I failed to update the npm packages, let me double check

**Comment by kaosat-dev** [comment]
Ok @z3dev  & @lorenzoaspesi  , this is now fixed here : (double checked with a clean install locally ) https://github.com/Spiritdude/OpenJSCAD.org/pull/238

**Comment by z3dev** [comment]
Fix for viewer RESET complete
Fix for Safari 9.1 complete (See jscad-api library)

I reviewed the code for handling mouse / touch events. Looks fine. Does hammerjs support touch devices?

**Comment by kaosat-dev** [comment]
Great @z3dev I just checked , reset works, just like resize
Yes , HammerJs is actually targeted at touch devices.

**Comment by z3dev** [comment]
Closing this issue in order to start  another round of testing.
