### ISSUE TITLE
Minus vector

### ISSUE THREAD

**Issue by derrickoswald** [Spiritdude/OpenJSCAD.org#27]
The printed gear bearing scad file:

```
http://www.thingiverse.com/thing:53451
```

when converted has an error because of this line:

```
translate(-[3,2.5])union(){
```

which cause a barf in the translate() method because of an invalid value.

This can be fixed by distributing the minus sign into the vector:

```
translate([-3,-2.5])union(){
```

but the better way would be to have the converter change it to a minus() operator or something.

**Comment by z3dev** [comment]
This issue was moved to jscad/openscad-openjscad-translator#7
