### ISSUE TITLE
Unable to use on Chrome Mobile 

### ISSUE THREAD

**Issue by The3rdIcon** [Spiritdude/OpenJSCAD.org#46]
I've been trying to use this on my mobile device, both tablet and phone. I've noticed that it requires WebGL to be enabled and have gone into the flags to make enable it. Despite enabling WebGL in Chrome on my mobile device non of the code that is type is in ever visualized like it is on laptop or desktop computer. Is there a simple solution that I could be missing?

**Comment by z3dev** [comment]
I have some changes pending for correcting the size of the canvas, and I have tested using Chrome on both iPhone and iPad. Can you try this URL and report back?

http://153.142.230.27:7443/openjscad/index.html

**Comment by z3dev** [comment]
Please try the latest version, as commit This was corrected by commit e262bec33168fce099a612044c715f89b80287a2 corrected a lot of issues with the canvas size.
