### ISSUE TITLE
WebGL not supported on Chrome or IE10?

### ISSUE THREAD

**Issue by Spiritdude** [Spiritdude/OpenJSCAD.org#5]
Someone posted on G+:

"Error: WebGL not supported

OpenJsCad currently requires Google Chrome with WebGL enabled"

Using Ubuntu 12.10 and google-chrome directly from google. WebGL works on other sites. Any tips?

**Comment by z3dev** [comment]
Works on Mac OSX with...
- Firefox 35.0
- Chrome 40.0
- Safari 8.0.2

**Comment by z3dev** [comment]
Works on iOS with...
- Safari aa
- Chrome 40.0
- Opera 9.1.0
- Mercury 8.9.4
But fails with...
- Puffin 4.1.2 (WebGL not supported)

**Comment by z3dev** [comment]
Works on Ubuntu 14.0 with...
- Firefox 31.0

**Comment by z3dev** [comment]
Closing.
I believe that all modern browsers support WebGL now.
