### ISSUE TITLE
Limitations on zoom - cannot view large or small sized objects.

### ISSUE THREAD

**Issue by twitchyliquid64** [Spiritdude/OpenJSCAD.org#52]
If I load an STL file of something that is small - the page will not let me zoom enough to see it proper (just a spec on the grid).

Likewise, if I make something too large, I cannot zoom out enough to see it. (In this case it was an openSCAD file of a table).

**Comment by z3dev** [comment]
The "view" has a default camera position.

With Version 0.5.0, the camera position can be changed. This should allow the view to be customized for small or large objects. Also, the grid size and "unit" can be changed as well.

Hope this helps

**Comment by z3dev** [comment]
@twitchyliquid64 I'm closing this as the last release allows the camera position to be adjusted.
