### ISSUE TITLE
Enhancement: SVG export

### ISSUE THREAD

**Issue by matthijskooijman** [Spiritdude/OpenJSCAD.org#54]
Having a direct SVG export feature would be helpful - it allows using the generated file directly in e.g. jscut. OpenSCAD also recently gained an SVG export, perhaps that might be useful to look at?

**Comment by z3dev** [comment]
I'm working on this functionality now. Is there specific functionality / features that you would like to have?

**Comment by z3dev** [comment]
@matthijskooijman FYI, this functionality was added in the latest version 0.5.0
