### ISSUE TITLE
Enhancement: Support setColor() for 2D objects (CAG)

### ISSUE THREAD

**Issue by matthijskooijman** [Spiritdude/OpenJSCAD.org#56]
It seems setColor is only supported for 3D objects? I'd need to color my 2D objects too, since our lasercutter uses color for deciding wether to cut, engrave or mark.

**Comment by z3dev** [comment]
I changed the title as this is really an enhancement request.

I also would like to see this functionality.

Sadly, the CSG library needs changes to support colors on 2D objects. There's no expected delivery date either.
