### ISSUE TITLE
transparency issue in setColor()

### ISSUE THREAD

**Issue by bebbi** [Spiritdude/OpenJSCAD.org#59]
I'm about to merge the alpha args in setColor into the joostn/csg.js rep. But there appears to be an issue with transparency. To reproduce:

function main() {
var red = CSG.cube({radius:10}).setColor(1, 0, 0, 0.5);
var green = CSG.cube({radius:10}).translate([3, 3, 3]).setColor(0, 1, 0, 0.5);
return [red, green];
// --> green is transparent, red is not transparent but should be.
}
Could you check this?

**Comment by Spiritdude** [comment]
@bebbi are you on G+ too? See https://plus.google.com/communities/114958480887231067224/stream/b799f5c4-b9bd-40ac-a7e9-5eeb49c99a6f

**Comment by tedbeer** [comment]
It's general WebGL/OpenGL issue. Read https://www.opengl.org/wiki/Transparency_Sorting. It would be too expensive for performance to support "true" transparency in browser.

**Comment by bebbi** [comment]
good info, thanks

**Comment by Spiritdude** [comment]
So, it's just a "problem" with the order of the elements? So, I close the issue then.

**Comment by tedbeer** [comment]
It's "just" an order. The order of elements depends from what point you look at the scene. So when you rotate the scene the order of elements how they are rendered also should be changed. 
And there is more complicated case when one element is in front of and behind of another element. For example a cube enclosed in a sphere.
All this 3D is a fake. They don't actually track every point of space and every light source. They just play with colors to simulate physical texture, shadows and lights and transparency.
