### ISSUE TITLE
cylinder diameter ignored

### ISSUE THREAD

**Issue by hrgdavor** [Spiritdude/OpenJSCAD.org#61]
I noticed this while testing simple openscad script
cylinder({h:4.5, d:9});
and
cylinder({h:4.5, r:4.5})
should be the same, but seems diameter "d" is not supported (only "r" is)

equivalent openscad code does not work too (the version with diameter "d" param)

simple openjscad test

function main() {
    return [
        cylinder({h:4.5, d:9}),
        translate([20,0,0],cylinder({h:4.5, r:4.5}))
        ];
}

**Comment by Spiritdude** [comment]
OpenJSCAD cylinder() does not support 'd', right - I add it in the next version of OpenJSCAD.org, along with d1/d2 support to follow OpenSCAD notion. OpenSCAD cylinder() should support 'd', but it seems the translator to OpenJSCAD doesn't pass it on. As soon I merged other pull requests the fix be available, thanks for the notification!
