### ISSUE TITLE
Enhancement: Show Compass

### ISSUE THREAD

**Issue by Jukkorsis** [Spiritdude/OpenJSCAD.org#62]
I would like to request a feature. Could a X/Y/Z compass (arrows in the positive direction) be displayed in the render panel. This would be very helpful. Thank you.

**Comment by z3dev** [comment]
@Jukkorsis This is now possible by setting options for the Viewer. The axis can be shown.

However, the default setting is the opposite, do NOT show. We haven't added display options to the main page yet. If you want the ability to change the settings then I will change keep this an an enhancement request.

**Comment by Jukkorsis** [comment]
Excellent, thanks for the update. The viewer should be fine.

----- Reply message -----
