### ISSUE TITLE
mirror(vec, object) doesn't properly mirror

### ISSUE THREAD

**Issue by richievos** [Spiritdude/OpenJSCAD.org#65]
The behavior of mirror doesn't reflect what OpenSCAD does, nor what I would expect it to do. I actually think the entire [mirror function](https://github.com/Spiritdude/OpenJSCAD.org/blob/08f603bac36d056a81ecaaf234a9217db48b9fc0/openscad.js#L659) needs to be reimplemented. I'm guessing when this was implemented it was a copy-paste of rotate (note the comment) and it doesn't actually work correctly like rotate. I have not yet tried rotate though, so I don't know if that is broken.

Existing code:
```javascript
function mirror(v,o) { 
   var a = arguments, v,o,i = 1, r = 0;
   if(arguments.length==3) {  // mirror(r,[x,y,z],o)
      r = a[0];
      v = a[1];
      i = 2;
      if(a[2].length) { a = a[2]; i = 0; }
      
   } else {                   // rotate([x,y,z],o)
      v = a[0];
      i = 1;
      if(a[1].length) { a = a[1]; i = 0; }
   }
   for(o=a[i++]; i<a.length; i++) { 
      o = o.union(a[i]);
   } 
   if(r!=1) {
      return o.mirroredX(v[0]*r).mirroredY(v[1]*r).mirroredZ(v[2]*r);
   } else {
      return o.mirroredX(v[0]).mirroredY(v[1]).mirroredZ(v[2]); 
   }
}
```

Notes:
* AFAICT these mirrored{X,Y,Z} functions don't take a parameter like that, so the whole r calc doesn't apply
* additionally, since those params don't matter, the code is *always* doing 3 mirrors
* [OpenSCAD mirror](http://en.wikibooks.org/wiki/OpenSCAD_User_Manual/The_OpenSCAD_Language#mirror) doesn't have 3 cases like what is described here. It has just a vec and objects

I believe the code should really be:

```javascript
function mirror(v) { 
   var o = null,
       i = 0,
       a = arguments.slice(1, arguments.length - 1);
   for(o=a[i++]; i<a.length; i++) { 
      o = o.union(a[i]);
   }

   var plane = new CSG.Plane(new CSG.Vector3D(v[0], v[1], v[2]), 0);
   return o.mirrored(plane);
}
```

Which I'll PR over in a bit, once I've finished testing.

**Comment by richievos** [comment]
**Example OpenSCAD code:**

```
module build_cube() {
  translate([3, 0, 0]) {
    cube(size=[4, 2, 2], center=true);
  }
}

build_cube();
mirror([1, 0, 0]) {
  build_cube();
}
mirror([1, 1, 0]) {
  build_cube();
}
mirror([1, 1, 0]) {
  mirror([1, 0, 0]) {
    build_cube();
  }
}
```

Should result in
![openscad_-_holder_scad](https://cloud.githubusercontent.com/assets/2414/6100906/05afbb44-afce-11e4-8d86-c4ae854eb791.png)


**Example OpenJSCAD code**

```javascript
function build_cube() {
  return translate([3, 0, 0], cube({size: [4, 2, 2], center: true}));
}

function main() {
  return [
    build_cube(),
    mirror([1, 0, 0], build_cube()),
    mirror([1, 1, 0], build_cube()),
    mirror([1, 1, 0],
           mirror([1, 0, 0], build_cube()))
  ];
}
```

Result:
![openjscad_org](https://cloud.githubusercontent.com/assets/2414/6100931/bb98182a-afce-11e4-98b6-78dce458482d.png)

**Comment by richievos** [comment]
Fixed code:

```javascript
function mirrorFixed(v) { 
   var a = Array.prototype.slice.call(arguments, 1, arguments.length),
       o = a[0];

   for(var i=1; i<a.length; i++) {
      o = o.union(a[i]);
   }
   var plane = new CSG.Plane(new CSG.Vector3D(v[0], v[1], v[2]).unit(), 0);
   return o.mirrored(plane);
}

function build_cube() {
  return translate([3, 0, 0], cube({size: [4, 2, 2], center: true}));
}

function main() {
  return [
    build_cube(),
    mirrorFixed([1, 0, 0], build_cube()),
    mirrorFixed([1, 1, 0], build_cube()),
    mirrorFixed([1, 1, 0],
                mirrorFixed([1, 0, 0], build_cube()))
  ];
}
```

![openjscad_org](https://cloud.githubusercontent.com/assets/2414/6101047/d7a7a85c-afd1-11e4-9ec8-fb75dbf488da.png)

**Comment by Spiritdude** [comment]
Thanks for the detailed documentation; see my comments on the pull request.
