### ISSUE TITLE
Disappearing polygons in polyhedron

### ISSUE THREAD

**Issue by dicoy** [Spiritdude/OpenJSCAD.org#67]
The following code draws and inverted pyramid, based on the example found in https://github.com/Spiritdude/OpenJSCAD.org/wiki/User-Guide#polyhedron

When rotating, some polygons disappear. This does not happen with the example code for some reason. Any clues?

function main(params) {
    
return polyhedron({
      		points: [
	  			[0,0,10], [10,10,20],[10,-10,20],
                  [-10,-10,20],[-10,10,20] 
	  		],
	  		triangles: [ 
	  			[1,2,0],[2,3,0],[3,4,0],[4,1,0],[1,2,3],[3,4,1]
                  
	  		]
		});
}

**Comment by Spiritdude** [comment]
Reverse the order of the points, you have to be aware of clock-wise / anti-clockwise when building polyhedrons this way.
