### ISSUE TITLE
Generated stl object is non manifold

### ISSUE THREAD

**Issue by chertykov** [Spiritdude/OpenJSCAD.org#77]
I have generated stl on [web site](http://openjscad.org/) from the following simplest code:

```
function main() {
   return difference(
         cube({size: 3, center: true}),
         cylinder({r:1, h:3, center: true}).rotateX(90)
      );
}
```

Then downloaded it and imported to Blender and checked for manifold.

![2015-03-05 20 26 45](https://cloud.githubusercontent.com/assets/329586/6510426/ffd38536-c376-11e4-8857-530901c10c3e.png)

**Comment by NateTG** [comment]
That probably has to do with having the cylinder's top and bottom coplanar with the faces of the cube somehow.  Have you tried h:3.5 with the cylinder?

**Comment by chertykov** [comment]
I have tried h:3.5 - no difference.

![2015-03-06 10 19 46](https://cloud.githubusercontent.com/assets/329586/6521563/940fd9d4-c3ea-11e4-871c-8f7c40279706.png)

**Comment by franzherzog** [comment]
Code with changes is working on http://joostn.github.io/OpenJsCad/processfile.html

```
function main() {

  var cube = CSG.cube({
    center:0,
    radius : 3
  });

  var cylinder = CSG.cylinder({
    radius:1,
    start: [0, -3, 0],
    end: [0, 3, 0],
  });

  var csg = cube.subtract(cylinder);
  return csg;


  /*
     code below created many manifold errors on stl export
  */

  /* return difference(
         cube({size: 3, center: true}),
         cylinder({r:1, h:3, center: true}).rotateX(90)
      );
  */
}
```

**Comment by hovissimo** [comment]
Any traction on this issue?

I'm having the same problem with a much more complicated part.
https://gist.github.com/hovissimo/ce5366a35834c3690488

Light blue lines show discontinuities: http://i.imgur.com/kDbFl6L.png

FWIW, this is worse with the AMF exporter.

**Comment by z3dev** [comment]
Pull request #107 contains some changes to CSG.js and openjscad.js. I ran some tests and all issues with T-junctions were resolved after making those changes.

If you need this fixed then please make the changes manually.

**Comment by z3dev** [comment]
This issue was moved to jscad/io#15
