### ISSUE TITLE
Feature Request: Handle to adjust code pane width

### ISSUE THREAD

**Issue by thehans** [Spiritdude/OpenJSCAD.org#79]
It would be nice to have a handle which can be dragged by mouse so the user may adjust the code pane width.  

I find the code pane to be too narrow if I tile two windows vertically, which I often do so I can reference OpenJSCAD documentation and other information in the adjacent window.

Another possible improvement could be a toggle to dock the code pane to the bottom instead of the side.

**Comment by z3dev** [comment]
I made a slight change that adds a tab to the editor, and allows the editor to be slide in/out on the right. Coming soon!

**Comment by z3dev** [comment]
This change is now available on the DEV branch.

**Comment by z3dev** [comment]
Closing.
OpenJSCAD.org 0.4.0 added a tab to the editor panel, which allows opening and closing the panel.
