### ISSUE TITLE
Google+ or here?

### ISSUE THREAD

**Issue by velociwabbit** [Spiritdude/OpenJSCAD.org#86]
I have been commenting on the google+ page for openjscad.org but the ideas/issues that I have been discussing are not end users but instead core development.  Is this the correct place to log them?

**Comment by Spiritdude** [comment]
Here are more the devs, whereas G+ are devs + end-users. So, you can post here too to be sure.

**Comment by velociwabbit** [comment]
great,

I have found some anomalies in the orthographic three.js camera and its
interactions with orbitcontrols. Still learning some of these libraries so
it might take another week or so to track down the bugs.

/jpr

**Comment by z3dev** [comment]
@velociwabbit 
I'm going to close this issue as this is really just an introduction.
You can post other issues via a separate thread. Please include an example as well.
Looking for to working with you.
