### ISSUE TITLE
Bad facet normals in .stl from csg.js based export (web & cli)

### ISSUE THREAD

**Issue by Spiritdude** [Spiritdude/OpenJSCAD.org#9]
Right now csg.js, in more concrete fixTJunctions() in the export chain to create .stl creates (edit: in few cases) bad facet normals, e.g. 'NaN' in the ascii export (both web or cli). E.g. when csg.toSTLString() without fixTJunction() then the .stl looks fine.

It wouldn't be such a big problem as most slicers disregard the normals, _but_ OpenJSCAD relies (at least for now) on proper set normals in order to determine the orientation of the triangles (cw vs ccw) and correct them (which means also, stl with bad normals cannot imported in general).

**Comment by z3dev** [comment]
#40 and this issue are about the same thing. Although possible, I'm not sure if the effort is worth it. There's no such thing as a "perfect" set of normals in STL. So, it's better to state the goal properly. Something like...

STL (and other formats) should be immediately usable by slicers.

Or

STL (and other formats) should be "error" free, i.e. not violating format models.

**Comment by swsnider** [comment]
Incorrect. This is not the same thing as #40. Please read the entire issue before proclaiming a dupe.

**Comment by sergerusso** [comment]
`CSG.polygon` calculates plane by first 3 vertices, but `fixTJunction` can add some more, like this 
```[[0,0,0],[0,0,50],[0,50,50]]``` ->  ```[[0,0,0],[0,0,25],[0,0,50],[0,50,50]]``` and it fails as we need 1, 3 and 4 vertex to do that.

Loop over all combo as a quick fix   sergerusso/OpenJSCAD.org@bbb27d380543bf46cca1eb5e5dfd90252fd5c989
Can be more elegant though

**Comment by z3dev** [comment]
Pull request #107 contains some changes to CSG.js and openjscad.js. I ran some tests and all issues with T-junctions were resolved after making those changes.

If you need this fixed then please make the changes manually.

**Comment by z3dev** [comment]
This issue was moved to jscad/io#17
