### ISSUE TITLE
Enhancement: Add preview of objects before rendering

### ISSUE THREAD

**Issue by g19fanatic** [Spiritdude/OpenJSCAD.org#98]
OpenSCAD supports an [interactive preview of the CSG geometry](http://www.opencsg.org/#References) through its use of the OpenCSG library. 

This feature is immensely useful for models that take greater than a few seconds to render and even more so for models that take minutes if not longer.

Would it be possible to provide a preview of the object being created before being able to _render_ that object and export it in a different format?

**Comment by z3dev** [comment]
In reality, the rendering of the geometry inside the the browser is the interactive view. There's not really another choice as the whole 3D engine is JavaScript. And the browser's 3D canvas is used to render the 3D geometry once compiled.

The command line script can be use for compiling OpenJsCad models into other formats, e.g. STL, DXF, etc.

By the way, one way to speed up rendering in the browser is by controlling the "resolution" being used for spheres, arches, etc. Use a low resolution when preparing the model, and use a high resolution when creating the final model for export.
